<template>
  <div class='loading'>
    <div class="loadingio-spinner-spinner-vivlunq8u6"><div class="ldio-osy37ll3cpb">
    <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
  </div>
  </div>
</template>

<script>
export default {
  name: 'Loading'
}
</script>

<style lang='scss'>
.loading {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 1000;
}
@keyframes ldio-osy37ll3cpb {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-osy37ll3cpb div {
  left: 47px;
  top: 26px;
  position: absolute;
  animation: ldio-osy37ll3cpb linear 1s infinite;
  background: #5c5e5c;
  width: 6px;
  height: 12px;
  border-radius: 3px / 6px;
  transform-origin: 3px 24px;
}.ldio-osy37ll3cpb div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #5c5e5c;
}.ldio-osy37ll3cpb div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #5c5e5c;
}.ldio-osy37ll3cpb div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #5c5e5c;
}.ldio-osy37ll3cpb div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #5c5e5c;
}.ldio-osy37ll3cpb div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #5c5e5c;
}.ldio-osy37ll3cpb div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #5c5e5c;
}.ldio-osy37ll3cpb div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #5c5e5c;
}.ldio-osy37ll3cpb div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #5c5e5c;
}.ldio-osy37ll3cpb div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #5c5e5c;
}.ldio-osy37ll3cpb div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #5c5e5c;
}.ldio-osy37ll3cpb div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #5c5e5c;
}.ldio-osy37ll3cpb div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #5c5e5c;
}
.loadingio-spinner-spinner-vivlunq8u6 {
  width: 100px;
  height: 100px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-osy37ll3cpb {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-osy37ll3cpb div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
